tap "hashicorp/tap"
brew "hashicorp/tap/terraform", trusted: true
brew "rclone"
cargo "tsql", source: "https://github.com/Avnerus/tsql.git?branch=fix-rustls-provider"
tap "gittower/tap"
brew "gittower/tap/git-flow-next", trusted: true
