tap "hashicorp/tap"
brew "hashicorp/tap/terraform", trusted: true
brew "rclone"
tap "fcoury/tap"
brew "fcoury/tap/tsql", trusted: true
tap "gittower/tap"
brew "gittower/tap/git-flow-next", trusted: true
