#! /usr/bin/env python3
import pathlib
import subprocess as sp
import sys

packages = [f"{pkg}" for pkg in sys.argv[1:]]

cmd = f"NIXPKGS_ALLOW_UNFREE=1 nix profile add --impure {' '.join([f'nixpkgs#{pkg}' for pkg in packages])}"
result = sp.run(cmd, shell=True)

if result.returncode == 0:
    home_nix_path = pathlib.Path.home() / '.local' / 'share' / 'chezmoi' / 'dot_config' / 'home-manager' / 'home.nix'
    packages_list_path = pathlib.Path.home() / '.local' / 'share' / 'chezmoi' / 'dot_config' / 'home-manager' / 'packages.txt'
    new_package_list = open(packages_list_path).read().splitlines() + packages
    with open(packages_list_path, "w") as ofile:
        ofile.write('n'.join(new_package_list))
    old_home_nix = open(home_nix_path).read()
    open(home_nix_path, "w").write(old_home_nix.replace("$$$$", "\n".join([f'\t\t{pkg}' for pkg in new_package_list])))
    sp.run(f"cd ~/.local/share/chezmoi && git add dot_config/home-manager/packages.txt dot_config/home-manager/home.nix && git commit -m 'add packages {' '.join(packages)}' && git push origin main", shell=True)
    sp.run("chezmoi apply ~/.config/home-manager/home.nix", shell=True)
