#! /usr/bin/env python3
import pathlib
import subprocess as sp
import sys

packages = [f"{pkg}" for pkg in sys.argv[1:]]

cmd = f"NIXPKGS_ALLOW_UNFREE=1 nix profile add --impure {' '.join([f'nixpkgs#{pkg}' for pkg in packages])}"
result = sp.run(cmd, shell=True)

if result.returncode == 0:
    home_dot_nix_path = f"{pathlib.Path.home() / '.local' / 'share' / 'chezmoi' / 'dot_config' / 'home-manager' / 'home.nix.tmpl'}"
    home_dot_nix = open(home_dot_nix_path, "r").read()
    new_home_dot_nix = home_dot_nix.replace('home.packages = with pkgs; [', 'home.packages = with pkgs; [\n' + '\n'.join(packages) + '\n')
    with open(home_dot_nix_path, "w") as ofile:
        ofile.write(new_home_dot_nix)
    sp.run("chezmoi git add dot_config/home-manager/home.nix && chezmoi git commit -m 'add packages' && chezmoi git push")
    sp.run("chezmoi apply ~/.config/home-manager/home.nix")
