#! /usr/bin/env python3

import sys
import os

import boto3

from ec2 import *

session = boto3.Session(profile_name='nuvobio')
ec2client = session.client("ec2")

instances = get_all_instances()
selected_instance = select_instance(instances, "Which instance do you want to toggle?")

instance_state = selected_instance.state

if instance_state == "stopped":
    response = ec2client.start_instances(
        InstanceIds=[
            selected_instance.id,
        ],
    )
    print(response)
elif instance_state == "running":
    response = ec2client.stop_instances(
        InstanceIds=[
            selected_instance.id,
        ],
    )
    print(response)
