#! /usr/bin/env python3
import argparse

import pandas as pd

parser = argparse.ArgumentParser(description='Joins tabular files if they have the same headers.')
parser.add_argument('-i', '--input', nargs='+', type=str, required=True, help='Path to the tabular files to merge.')
parser.add_argument('-f', '--format', choices=['csv', 'tsv'], type=str, required=False, default='csv', help='Format of the files (CSV or TSV).')
parser.add_argument('-o', '--output', type=str, required=True, help='Path to the resulting file.')
args = vars(parser.parse_args())

# Set delimiter
delimiter = '\t' if args['format'] == 'tsv' else ','

# Load the dataframes
dfs = [pd.read_csv(input_file, sep=delimiter) for input_file in args['input']]

# Check that the headers match
columns = list(dfs[0].columns)

if not all([list(df.columns) == columns for df in dfs]):
    raise "The columns don't match... check that the columns of all files are the same."

# Merge and save
merged = pd.concat(dfs)
merged.to_csv(args['output'], sep=delimiter, index=False)
