#! /usr/bin/env python3
import os
import pathlib
import subprocess as sp

if os.path.exists(os.path.join(str(pathlib.Path.home()), '.fonts')):
    sp.run("cd $HOME/.fonts && git pull origin main", shell=True)
else:
    sp.run("cd && git clone git@github.com:fcharih/.fonts.git", shell=True)
